import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { patchComplianceAttestation } from '../src/ops/compliance-attestation.mjs';

const ROOT=fileURLToPath(new URL('../',import.meta.url));
function fixture(){return{accountsConfig:{accounts:{alpha:{platform:'x',enabled:true,mode:'auto',engagement:{approvalRequired:false}},ig:{platform:'instagram',enabled:true,mode:'auto'}}},policy:{enabled:true,liveAccounts:['alpha'],xAutomationProfileComplianceConfirmedAccounts:[],xAiReplyBotApprovalRequiredAccounts:['alpha'],xAiReplyBotApprovalConfirmedAccounts:[]}}}

test('profile confirmation records only an explicit repository attestation and activates nothing',()=>{const {accountsConfig,policy}=fixture();const result=patchComplianceAttestation({accountsConfig,policy,accountId:'alpha',kind:'x-profile',confirmed:true});assert.deepEqual(result.policy.xAutomationProfileComplianceConfirmedAccounts,['alpha']);assert.deepEqual(result.policy.liveAccounts,['alpha']);assert.equal(result.accountsConfig.accounts.alpha.mode,'auto');assert.deepEqual(policy.xAutomationProfileComplianceConfirmedAccounts,[])});
test('AI reply confirmation is allowed only when the account is configured as requiring it',()=>{const {accountsConfig,policy}=fixture();const result=patchComplianceAttestation({accountsConfig,policy,accountId:'alpha',kind:'x-ai-reply',confirmed:true});assert.deepEqual(result.policy.xAiReplyBotApprovalConfirmedAccounts,['alpha']);assert.throws(()=>patchComplianceAttestation({accountsConfig,policy:{...policy,xAiReplyBotApprovalRequiredAccounts:[]},accountId:'alpha',kind:'x-ai-reply',confirmed:true}),error=>error.code==='COMPLIANCE_AI_REPLY_NOT_REQUIRED')});
test('profile revocation immediately pauses publishing and removes unattended engagement',()=>{const {accountsConfig,policy}=fixture();policy.xAutomationProfileComplianceConfirmedAccounts=['alpha'];const result=patchComplianceAttestation({accountsConfig,policy,accountId:'alpha',kind:'x-profile',confirmed:false});assert.deepEqual(result.policy.liveAccounts,[]);assert.deepEqual(result.policy.xAutomationProfileComplianceConfirmedAccounts,[]);assert.equal(result.accountsConfig.accounts.alpha.mode,'pause');assert.equal(result.accountsConfig.accounts.alpha.engagement.approvalRequired,true)});
test('AI reply approval revocation disables unattended engagement without unnecessarily pausing ordinary posting',()=>{const {accountsConfig,policy}=fixture();policy.xAiReplyBotApprovalConfirmedAccounts=['alpha'];const result=patchComplianceAttestation({accountsConfig,policy,accountId:'alpha',kind:'x-ai-reply',confirmed:false});assert.deepEqual(result.policy.liveAccounts,[]);assert.deepEqual(result.policy.xAiReplyBotApprovalConfirmedAccounts,[]);assert.equal(result.accountsConfig.accounts.alpha.mode,'auto');assert.equal(result.accountsConfig.accounts.alpha.engagement.approvalRequired,true)});
test('attestations reject unknown, non-X, and malformed inputs',()=>{const {accountsConfig,policy}=fixture();assert.throws(()=>patchComplianceAttestation({accountsConfig,policy,accountId:'missing',kind:'x-profile',confirmed:true}),error=>error.code==='COMPLIANCE_ACCOUNT_UNKNOWN');assert.throws(()=>patchComplianceAttestation({accountsConfig,policy,accountId:'ig',kind:'x-profile',confirmed:true}),error=>error.code==='COMPLIANCE_X_ONLY');assert.throws(()=>patchComplianceAttestation({accountsConfig,policy,accountId:'alpha',kind:'other',confirmed:true}),error=>error.code==='COMPLIANCE_KIND_INVALID');assert.throws(()=>patchComplianceAttestation({accountsConfig,policy,accountId:'bad id',kind:'x-profile',confirmed:true}),error=>error.code==='COMPLIANCE_ACCOUNT_ID_INVALID')});
test('workflow requires exact human attestation markers and supports safe revocation',async()=>{const workflow=await readFile(`${ROOT}.github/workflows/compliance-attestation.yml`,'utf8');assert.match(workflow,/I_CONFIRM_X_AUTOMATED_PROFILE_SETUP_COMPLETE=true/);assert.match(workflow,/I_CONFIRM_X_AI_REPLY_WRITTEN_APPROVAL_RECEIVED=true/);assert.match(workflow,/\[compliance-revoke-x-profile\]/);assert.match(workflow,/\[compliance-revoke-x-ai-reply\]/);assert.match(workflow,/SNS_COMMAND_ADMINS/);assert.match(workflow,/git add config\/accounts\.json config\/engagement-policy\.json/);assert.doesNotMatch(workflow,/cancel-in-progress:\s*true/)});
