import assert from 'node:assert/strict';
import test from 'node:test';
import { validateHubProductContract } from '../src/hub/product-contract.mjs';

const valid={schemaVersion:1,productId:'sample-product',slug:'sample-product',name:'Sample',brand:'Brand',kind:'physical',categoryIds:['home'],problemTagIds:['cleaning'],problemSolved:'Reduce a repeated task',convenienceInOneSentence:'Useful in one sentence',whyInteresting:'Interesting reason',whoFor:['someone'],whoCanSkip:['someone else'],tradeoffs:['one tradeoff'],officialUrl:'https://example.com/item',media:[],pricing:{display:null,currency:'JPY',verifiedAt:null},availability:'available',scores:{discoverySurprise:50,practicalUtility:50,clarity:50,evidenceStrength:50,audienceFit:50,valueSense:50,distinctiveness:50,shareability:50,risk:10},routes:[{routeId:'route-one',provider:'direct',merchant:'Official',url:'https://example.com/item',routeType:'official',platforms:['hub'],status:'ACTIVE',destinationProductMatch:true,verifiedAt:'2026-08-14T00:00:00Z',disclosureRequired:false,notes:null}],alternatives:[],social:[],freshness:{lastProductVerifiedAt:'2026-08-14T00:00:00Z',lastPriceVerifiedAt:null,lastAffiliateRouteVerifiedAt:'2026-08-14T00:00:00Z'},publication:{status:'ready',firstPublishedAt:null,updatedAt:'2026-08-14T00:00:00Z'}};
const copy=()=>structuredClone(valid);

test('complete canonical product passes the mirrored Hub contract',()=>assert.equal(validateHubProductContract(copy(),{requireReady:true}).productId,'sample-product'));
test('missing and unknown top-level fields fail before cross-repository write',()=>{const missing=copy();delete missing.categoryIds;assert.throws(()=>validateHubProductContract(missing),/categoryIds is required/);assert.throws(()=>validateHubProductContract({...copy(),unexpected:true}),/unexpected is not allowed/)});
test('score bounds and exact-price verification are enforced',()=>{const score=copy();score.scores.risk=101;assert.throws(()=>validateHubProductContract(score),/risk must be 0\.\.100/);const price=copy();price.pricing.display='¥1,000';assert.throws(()=>validateHubProductContract(price),/requires verifiedAt/)});
test('route identity, exact-product match and affiliate disclosure are enforced',()=>{const affiliate=copy();affiliate.routes[0].routeType='affiliate';assert.throws(()=>validateHubProductContract(affiliate),/affiliate route must require disclosure/);const mismatch=copy();mismatch.routes[0].destinationProductMatch=false;assert.throws(()=>validateHubProductContract(mismatch),/ACTIVE route must match/);const duplicate=copy();duplicate.routes.push(structuredClone(duplicate.routes[0]));assert.throws(()=>validateHubProductContract(duplicate),/duplicate route-one/)});
test('ready staging cannot import already-published social backlinks',()=>{const product=copy();product.social=[{platform:'x',postId:'1',url:'https://x.com/i/web/status/1',publishedAt:'2026-08-14T01:00:00Z'}];assert.throws(()=>validateHubProductContract(product,{requireReady:true}),/must not contain already-published social backlinks/)});
test('nested additional properties are rejected just like SNS-HUB JSON Schema',()=>{const product=copy();product.routes[0].commissionRate=99;assert.throws(()=>validateHubProductContract(product),/commissionRate is not allowed/)});
