import assert from 'node:assert/strict';
import test from 'node:test';
import { prepareHubPublish } from '../src/hub/prepare.mjs';
import { publish } from '../src/publish.mjs';

test('prepare stages canonical product then waits for exact deploy version',async()=>{const order=[];const result=await prepareHubPublish({productId:'p1'},{stage:async()=>{order.push('stage');return{expectedContentVersion:'aaaaaaaaaaaaaaaaaaaa',commitSha:'abc'}},waitReady:async(input)=>{order.push('wait');assert.equal(input.expectedContentVersion,'aaaaaaaaaaaaaaaaaaaa');return{ready:true}}});assert.deepEqual(order,['stage','wait']);assert.deepEqual(result.hub,{required:true,integration:'convenience-discovery-v1',productId:'p1',expectedContentVersion:'aaaaaaaaaaaaaaaaaaaa'});assert.equal(result.readiness.ready,true)});

test('canonical hubProduct auto-stages before readiness gate and provider core without leaking full product downstream',async()=>{const order=[];let claim=null,corePayload=null;const hub={required:true,integration:'convenience-discovery-v1',productId:'p1',expectedContentVersion:'aaaaaaaaaaaaaaaaaaaa'};const result=await publish({account:'c',slotId:'s',hubProduct:{productId:'p1',whyInteresting:'large canonical data'}},{getClaim:async()=>claim,prepare:async()=>{order.push('prepare');return{hub}},assertBefore:async()=>{order.push('ready')},writeClaim:async(_s,status,detail)=>{claim={status,hub:detail.hub};order.push('claim');return claim},core:async(payload)=>{corePayload=payload;order.push('core');claim={...claim,status:'published',providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};return{postId:'x1'}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{order.push('sync');return{sync:{changed:true}}},audit:async()=>{}});assert.deepEqual(order,['prepare','ready','claim','core','sync']);assert.equal(result.hub.synced,true);assert.equal('hubProduct' in corePayload,false);assert.deepEqual(corePayload.hub,hub)});

test('explicit Hub envelope also strips an incidental hubProduct before core',async()=>{let corePayload=null,claim=null;const hub={required:true,integration:'convenience-discovery-v1',productId:'p1',expectedContentVersion:'aaaaaaaaaaaaaaaaaaaa'};await publish({account:'c',slotId:'s',hub,hubProduct:{productId:'p1'}},{getClaim:async()=>claim,writeClaim:async(_s,status,detail)=>{claim={status,...detail};return claim},assertBefore:async()=>{},core:async(payload)=>{corePayload=payload;claim={...claim,status:'published',providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};return{postId:'x1'}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>({sync:{changed:false}}),audit:async()=>{}});assert.equal('hubProduct' in corePayload,false);assert.deepEqual(corePayload.hub,hub)});

test('dry-run hubProduct validates locally, never mutates SNS-HUB, and does not pass canonical product into core',async()=>{let prepareCalls=0,validationCalls=0,corePayload=null;const result=await publish({account:'c',slotId:'s',hubProduct:{productId:'p1'},dryRun:true},{getClaim:async()=>null,prepare:async()=>{prepareCalls++;throw new Error('must not stage')},validateProduct:(product,options)=>{validationCalls++;assert.equal(product.productId,'p1');assert.equal(options.requireReady,true)},core:async(payload)=>{corePayload=payload;return{dryRun:true}}});assert.equal(result.dryRun,true);assert.equal(prepareCalls,0);assert.equal(validationCalls,1);assert.equal('hubProduct' in corePayload,false)});
