import assert from 'node:assert/strict';
import test from 'node:test';
import { publish } from '../src/publish.mjs';

const hub={required:true,integration:'convenience-discovery-v1',productId:'p1',expectedContentVersion:'aaaaaaaaaaaaaaaaaaaa'};

test('unrelated publish bypasses all Hub-specific guards and writes',async()=>{let hubCalls=0;const result=await publish({account:'other'},{core:async()=>({postId:'1'}),getClaim:async()=>null,writeClaim:async()=>{hubCalls++},assertBefore:async()=>{hubCalls++},syncBacklink:async()=>{hubCalls++}});assert.deepEqual(result,{postId:'1'});assert.equal(hubCalls,0)});
test('new Hub publish asserts readiness and durably stores Hub metadata before core',async()=>{const order=[];let claim=null;const result=await publish({account:'c',slotId:'s',hub},{getClaim:async()=>claim,assertBefore:async()=>{order.push('ready')},writeClaim:async(_s,status,detail)=>{order.push(`claim:${status}`);claim={status,hub:detail.hub};return claim},core:async()=>{order.push('core');claim={...claim,status:'published',providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};return{postId:'x1'}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{order.push('sync');return{sync:{changed:true}}},audit:async()=>{}});assert.deepEqual(order.slice(0,4),['ready','claim:hub_ready','core','sync']);assert.equal(result.hub.synced,true)});
test('published durable replay skips readiness and retries only Hub synchronization',async()=>{let ready=0,core=0,sync=0;const claim={status:'published',hub,providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};const result=await publish({account:'c',slotId:'s'},{getClaim:async()=>claim,writeClaim:async()=>claim,assertBefore:async()=>{ready++},core:async()=>{core++;return{postId:'x1',idempotentReplay:true}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{sync++;return{sync:{changed:false}}},audit:async()=>{}});assert.equal(ready,0);assert.equal(core,1);assert.equal(sync,1);assert.equal(result.idempotentReplay,true)});
test('Hub sync failure after provider success becomes HUB_BACKLINK_PENDING while published claim survives',async()=>{let writes=0,core=0;let claim=null;await assert.rejects(()=>publish({account:'c',slotId:'s',hub},{getClaim:async()=>claim,assertBefore:async()=>{},writeClaim:async(_s,status,detail)=>{writes++;claim={...(claim||{}),status,...detail};return claim},core:async()=>{core++;claim={...claim,status:'published',providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};return{postId:'x1'}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{throw new Error('hub down')},sleepImpl:async()=>{},audit:async()=>{}}),error=>error.code==='HUB_BACKLINK_PENDING'&&error.providerResult?.postId==='x1');assert.equal(core,1);assert.equal(claim.status,'published');assert.equal(writes,1)});
test('Hub live publish without slotId fails before core',async()=>{let core=0;await assert.rejects(()=>publish({account:'c',hub},{getClaim:async()=>null,writeClaim:async()=>{},assertBefore:async()=>{},core:async()=>{core++}}),error=>error.code==='HUB_SLOT_REQUIRED');assert.equal(core,0)});
test('dry run validates opt-in but never needs Hub readiness or durable preparation',async()=>{let ready=0,writes=0;const result=await publish({account:'c',hub,dryRun:true,slotId:'s'},{getClaim:async()=>null,writeClaim:async()=>{writes++},assertBefore:async()=>{ready++},core:async()=>({dryRun:true})});assert.deepEqual(result,{dryRun:true});assert.equal(ready,0);assert.equal(writes,0)});
