import assert from 'node:assert/strict';
import test from 'node:test';
import { publish } from '../src/publish.mjs';

const hub={required:true,integration:'convenience-discovery-v1',productId:'p1',expectedContentVersion:'aaaaaaaaaaaaaaaaaaaa'};

test('unrelated publish bypasses all Hub-specific guards and writes',async()=>{let hubCalls=0;const result=await publish({account:'other'},{core:async()=>({postId:'1'}),getClaim:async()=>null,writeClaim:async()=>{hubCalls++},assertBefore:async()=>{hubCalls++},syncBacklink:async()=>{hubCalls++}});assert.deepEqual(result,{postId:'1'});assert.equal(hubCalls,0)});
test('new Hub publish asserts readiness, publishes once, syncs backlink, and records reconciliation marker',async()=>{const order=[];let claim=null;const result=await publish({account:'c',slotId:'s',hub},{getClaim:async()=>claim,assertBefore:async()=>{order.push('ready')},writeClaim:async(_s,status,detail)=>{order.push(`claim:${status}`);claim={...(claim||{}),status,...detail};return claim},core:async()=>{order.push('core');claim={...claim,status:'published',providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};return{postId:'x1'}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{order.push('sync');return{url:'https://x.com/i/web/status/x1',sync:{changed:true}}},now:()=>new Date('2026-08-14T00:01:00Z'),audit:async()=>{}});assert.deepEqual(order,['ready','claim:hub_ready','core','sync','claim:published']);assert.equal(result.hub.synced,true);assert.equal(result.hub.markerPersisted,true);assert.equal(claim.hubBacklinkSyncedAt,'2026-08-14T00:01:00.000Z')});
test('published durable replay skips readiness and retries only Hub synchronization',async()=>{let ready=0,core=0,sync=0;let claim={status:'published',slotId:'s',account:'c',hub,providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};const result=await publish({account:'c',slotId:'s'},{getClaim:async()=>claim,writeClaim:async(_s,status,detail)=>{claim={...claim,status,...detail};return claim},assertBefore:async()=>{ready++},core:async()=>{core++;return{postId:'x1',idempotentReplay:true}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{sync++;return{url:'https://x.com/i/web/status/x1',sync:{changed:false}}},audit:async()=>{}});assert.equal(ready,0);assert.equal(core,1);assert.equal(sync,1);assert.equal(result.idempotentReplay,true);assert.equal(result.hub.markerPersisted,true)});
test('wrapper repairs a non-published durable claim before exposing Hub backlink',async()=>{const order=[];let claim={status:'publishing',hub};const result=await publish({account:'c',slotId:'s'},{getClaim:async()=>claim,writeClaim:async(_s,status,detail)=>{order.push(`claim:${status}`);claim={...claim,status,...detail};return claim},core:async()=>{order.push('core');return{postId:'x1'}},resolve:async()=>({platform:'x'}),syncBacklink:async({claim:seen})=>{order.push('sync');assert.equal(seen.status,'published');assert.equal(seen.providerPostId,'x1');return{url:'https://x.com/i/web/status/x1',sync:{changed:true}}},audit:async()=>{}});assert.deepEqual(order,['core','claim:published','sync','claim:published']);assert.equal(result.hub.synced,true)});
test('durable published persistence failure stops before Hub backlink and preserves provider result',async()=>{let sync=0,writes=0;const claim={status:'publishing',hub};await assert.rejects(()=>publish({account:'c',slotId:'s'},{getClaim:async()=>claim,writeClaim:async()=>{writes++;throw new Error('durable unavailable')},core:async()=>({postId:'x1'}),resolve:async()=>({platform:'x'}),syncBacklink:async()=>{sync++;return{sync:{changed:true}}},sleepImpl:async()=>{},audit:async()=>{}}),error=>error.code==='HUB_DURABLE_PENDING'&&error.providerResult?.postId==='x1');assert.equal(writes,3);assert.equal(sync,0)});
test('Hub sync failure after provider success becomes HUB_BACKLINK_PENDING while published claim survives',async()=>{let writes=0,core=0;let claim=null;await assert.rejects(()=>publish({account:'c',slotId:'s',hub},{getClaim:async()=>claim,assertBefore:async()=>{},writeClaim:async(_s,status,detail)=>{writes++;claim={...(claim||{}),status,...detail};return claim},core:async()=>{core++;claim={...claim,status:'published',providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};return{postId:'x1'}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{throw new Error('hub down')},sleepImpl:async()=>{},audit:async()=>{}}),error=>error.code==='HUB_BACKLINK_PENDING'&&error.providerResult?.postId==='x1');assert.equal(core,1);assert.equal(claim.status,'published');assert.equal(writes,1)});
test('marker persistence failure does not republish or hide successful Hub sync',async()=>{let core=0,sync=0;const claim={status:'published',slotId:'s',account:'c',hub,providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};const result=await publish({account:'c',slotId:'s'},{getClaim:async()=>claim,writeClaim:async()=>{throw new Error('state branch temporarily unavailable')},core:async()=>{core++;return{postId:'x1',idempotentReplay:true}},resolve:async()=>({platform:'x'}),syncBacklink:async()=>{sync++;return{url:'https://x.com/i/web/status/x1',sync:{changed:false}}},audit:async()=>{}});assert.equal(core,1);assert.equal(sync,1);assert.equal(result.hub.synced,true);assert.equal(result.hub.markerPersisted,false)});
test('hub backlink marker write does not null-clobber providerPostId or publishedAt',async()=>{let written=null;const claim={status:'published',slotId:'s',account:'c',hub,providerPostId:'x1',publishedAt:'2026-08-14T00:00:00Z'};await publish({account:'c',slotId:'s'},{getClaim:async()=>claim,writeClaim:async(_s,status,detail)=>{written={status,...detail};return{...claim,...written}},core:async()=>({postId:'x1',idempotentReplay:true}),resolve:async()=>({platform:'x'}),syncBacklink:async()=>({url:'https://x.com/i/web/status/x1',sync:{changed:false}}),audit:async()=>{}});assert.equal(written.providerPostId,'x1');assert.equal(written.publishedAt,'2026-08-14T00:00:00Z');assert.ok(written.hubBacklinkSyncedAt);assert.equal(Object.hasOwn(written,'providerPostId')&&written.providerPostId===null,false)});
test('hub backlink marker omits missing provenance fields instead of writing null',async()=>{let written=null;const claim={status:'published',slotId:'s',account:'c',hub};await publish({account:'c',slotId:'s'},{getClaim:async()=>claim,writeClaim:async(_s,status,detail)=>{written={status,...detail};return{...claim,...written}},core:async()=>({postId:null,idempotentReplay:true}),resolve:async()=>({platform:'x'}),syncBacklink:async()=>({url:'https://x.com/i/web/status/x1',sync:{changed:false}}),audit:async()=>{}});assert.equal(Object.hasOwn(written,'providerPostId'),false);assert.equal(Object.hasOwn(written,'publishedAt'),false);assert.ok(written.hubBacklinkSyncedAt)});
test('Hub live publish without slotId fails before core',async()=>{let core=0;await assert.rejects(()=>publish({account:'c',hub},{getClaim:async()=>null,writeClaim:async()=>{},assertBefore:async()=>{},core:async()=>{core++}}),error=>error.code==='HUB_SLOT_REQUIRED');assert.equal(core,0)});
test('dry run validates opt-in but never needs Hub readiness or durable preparation',async()=>{let ready=0,writes=0;const result=await publish({account:'c',hub,dryRun:true,slotId:'s'},{getClaim:async()=>null,writeClaim:async()=>{writes++},assertBefore:async()=>{ready++},core:async()=>({dryRun:true})});assert.deepEqual(result,{dryRun:true});assert.equal(ready,0);assert.equal(writes,0)});
