import assert from 'node:assert/strict';
import test from 'node:test';
import crypto from 'node:crypto';
import {attachBacklinkToProduct,attachHubSocialBacklink,computeExpectedContentVersion,getHubReadiness,hubConfig,mergeCanonicalProduct,stableStringify,stageHubProduct} from '../src/hub/convenience-hub.mjs';

const env={CONVENIENCE_HUB_REPOSITORY:'owner/SNS-HUB',CONVENIENCE_HUB_GITHUB_TOKEN:'hub-only-token',CONVENIENCE_HUB_BRANCH:'main',CONVENIENCE_HUB_PUBLIC_URL:'https://hub.example'};
const baseProduct={schemaVersion:1,productId:'sample-product',slug:'sample-product',name:'Sample',brand:'Brand',kind:'physical',categoryIds:['home'],problemTagIds:['cleaning'],problemSolved:'x',convenienceInOneSentence:'y',whyInteresting:'z',whoFor:['a'],whoCanSkip:['b'],tradeoffs:['c'],officialUrl:'https://example.com/item',media:[],pricing:{display:null,currency:'JPY',verifiedAt:null},availability:'available',scores:{discoverySurprise:1,practicalUtility:1,clarity:1,evidenceStrength:1,audienceFit:1,valueSense:1,distinctiveness:1,shareability:1,risk:1},routes:[{routeId:'route-one',provider:'direct',merchant:'Official',url:'https://example.com/item',routeType:'official',platforms:['hub'],status:'ACTIVE',destinationProductMatch:true,verifiedAt:'2026-08-14T00:00:00Z',disclosureRequired:false,notes:null}],alternatives:[],social:[],freshness:{lastProductVerifiedAt:'2026-08-14T00:00:00Z',lastPriceVerifiedAt:null,lastAffiliateRouteVerifiedAt:null},publication:{status:'ready',firstPublishedAt:null,updatedAt:'2026-08-14T00:00:00Z'}};
function jsonResponse(status,data){return {ok:status>=200&&status<300,status,async json(){return data}}}
function filePayload(data,sha='blob'){return {type:'file',encoding:'base64',sha,content:Buffer.from(JSON.stringify(data)).toString('base64')}}

test('hub config never falls back to generic GitHub token',()=>{assert.throws(()=>hubConfig({...env,CONVENIENCE_HUB_GITHUB_TOKEN:'',GITHUB_TOKEN:'generic'}),/CONVENIENCE_HUB_GITHUB_TOKEN/)});
test('canonical merge preserves social/history, keeps published, and treats routes as authoritative',()=>{const existing=structuredClone(baseProduct);existing.publication.status='published';existing.publication.firstPublishedAt='2026-08-01T00:00:00Z';existing.social=[{platform:'x',postId:'old',url:'https://x.com/i/web/status/1',publishedAt:'2026-08-01T00:00:00Z'}];const incoming=structuredClone(baseProduct);incoming.routes=[];const merged=mergeCanonicalProduct(existing,incoming);assert.equal(merged.publication.status,'published');assert.equal(merged.publication.firstPublishedAt,'2026-08-01T00:00:00Z');assert.equal(merged.social.length,1);assert.deepEqual(merged.routes,[])});
test('stage rejects secret fields and requires ready state',async()=>{await assert.rejects(()=>stageHubProduct({...structuredClone(baseProduct),credential:{token:'x'}},{env,fetchImpl:async()=>{throw new Error('network should not run')}}),/credential/);await assert.rejects(()=>stageHubProduct({...structuredClone(baseProduct),publication:{...baseProduct.publication,status:'published'}},{env,fetchImpl:async()=>{throw new Error('network should not run')}}),/status=ready|staging requires/)});
test('expected contentVersion matches Hub stable snapshot algorithm',async()=>{const categories=[{id:'home',slug:'home',label:'Home',description:'x'}],problems=[{id:'cleaning',slug:'cleaning',label:'Cleaning',description:'x'}],product=structuredClone(baseProduct);const calls=[];const fetchImpl=async(url)=>{calls.push(url);if(url.includes('/data/categories.json?'))return jsonResponse(200,filePayload(categories));if(url.includes('/data/problem-tags.json?'))return jsonResponse(200,filePayload(problems));if(url.includes('/contents/data/products?'))return jsonResponse(200,[{type:'file',name:'sample-product.json',path:'data/products/sample-product.json'}]);if(url.includes('/data/products/sample-product.json?'))return jsonResponse(200,filePayload(product));throw new Error(`unexpected ${url}`)};const actual=await computeExpectedContentVersion({env,fetchImpl,ref:'abc'});const snapshot={categories,problemTags:problems,products:[product]};const expected=crypto.createHash('sha256').update(stableStringify(snapshot)).digest('hex').slice(0,20);assert.equal(actual,expected);assert.equal(calls.some((u)=>u.includes('/go/')),false)});
test('readiness fails closed on version mismatch and only probes health URLs',async()=>{const calls=[];const fetchImpl=async(url)=>{calls.push(url);if(url.endsWith('/_health/content-version'))return jsonResponse(200,{ok:true,contentVersion:'11111111111111111111'});if(url.endsWith('/_health/product/sample-product'))return jsonResponse(200,{ok:true,publishReady:true,publiclyReachable:true,productId:'sample-product',contentVersion:'22222222222222222222',publicUrl:'https://hub.example/p/sample-product'});throw new Error('unexpected')};const result=await getHubReadiness({productId:'sample-product',expectedContentVersion:'aaaaaaaaaaaaaaaaaaaa'},{env,fetchImpl});assert.equal(result.ready,false);assert.equal(calls.every((u)=>u.includes('/_health/')),true)});
test('readiness requires exact version and stable public URL on configured origin',async()=>{const version='aaaaaaaaaaaaaaaaaaaa';const fetchImpl=async(url)=>url.endsWith('/_health/content-version')?jsonResponse(200,{ok:true,contentVersion:version}):jsonResponse(200,{ok:true,publishReady:true,publiclyReachable:true,productId:'sample-product',contentVersion:version,publicUrl:'https://hub.example/p/sample-product'});const result=await getHubReadiness({productId:'sample-product',expectedContentVersion:version},{env,fetchImpl});assert.equal(result.ready,true)});
test('social backlinks publish ready product, preserve each platform, and replay is no-op',()=>{const x={platform:'x',postId:'x1',url:'https://x.com/i/web/status/1',publishedAt:'2026-08-14T01:00:00Z'};const first=attachBacklinkToProduct(structuredClone(baseProduct),x,'2026-08-14T01:01:00Z');assert.equal(first.product.publication.status,'published');assert.equal(first.product.publication.firstPublishedAt,x.publishedAt);const replay=attachBacklinkToProduct(first.product,x,'2026-08-14T01:02:00Z');assert.equal(replay.changed,false);const ig=attachBacklinkToProduct(first.product,{platform:'instagram',postId:'ig1',url:'https://www.instagram.com/p/example/',publishedAt:'2026-08-14T02:00:00Z'},'2026-08-14T02:01:00Z');assert.equal(ig.product.social.length,2);assert.equal(ig.product.social.filter((s)=>s.platform==='x').length,1);assert.equal(ig.product.social.filter((s)=>s.platform==='instagram').length,1)});
test('stage creates file and computes version against exact returned commit',async()=>{const product=structuredClone(baseProduct),categories=[{id:'home',slug:'home',label:'Home',description:'x'}],problems=[{id:'cleaning',slug:'cleaning',label:'Cleaning',description:'x'}];let putBody=null;const fetchImpl=async(url,options={})=>{if(options.method==='PUT'){putBody=JSON.parse(options.body);return jsonResponse(200,{commit:{sha:'commit123'},content:{sha:'newblob'}})}if(url.includes('/data/products/sample-product.json?ref=main'))return jsonResponse(404,{message:'Not Found'});if(url.includes('/data/categories.json?ref=commit123'))return jsonResponse(200,filePayload(categories));if(url.includes('/data/problem-tags.json?ref=commit123'))return jsonResponse(200,filePayload(problems));if(url.includes('/contents/data/products?ref=commit123'))return jsonResponse(200,[{type:'file',name:'sample-product.json',path:'data/products/sample-product.json'}]);if(url.includes('/data/products/sample-product.json?ref=commit123'))return jsonResponse(200,filePayload(product));throw new Error(`unexpected ${options.method||'GET'} ${url}`)};const result=await stageHubProduct(product,{env,fetchImpl});assert.equal(result.commitSha,'commit123');assert.match(result.expectedContentVersion,/^[a-f0-9]{20}$/);assert.equal(putBody.branch,'main');assert.equal('sha' in putBody,false)});
test('stage safely re-reads and re-merges after a GitHub write conflict',async()=>{const incoming=structuredClone(baseProduct),old={...structuredClone(baseProduct),name:'Older name'},categories=[{id:'home',slug:'home',label:'Home',description:'x'}],problems=[{id:'cleaning',slug:'cleaning',label:'Cleaning',description:'x'}];let mainReads=0,puts=0;const fetchImpl=async(url,options={})=>{if(url.includes('/data/products/sample-product.json?ref=main')){mainReads++;return jsonResponse(200,filePayload(old,`blob-${mainReads}`))}if(options.method==='PUT'){puts++;if(puts===1)return jsonResponse(409,{message:'sha does not match'});return jsonResponse(200,{commit:{sha:'commit-after-conflict'},content:{sha:'newblob'}})}if(url.includes('/data/categories.json?ref=commit-after-conflict'))return jsonResponse(200,filePayload(categories));if(url.includes('/data/problem-tags.json?ref=commit-after-conflict'))return jsonResponse(200,filePayload(problems));if(url.includes('/contents/data/products?ref=commit-after-conflict'))return jsonResponse(200,[{type:'file',name:'sample-product.json',path:'data/products/sample-product.json'}]);if(url.includes('/data/products/sample-product.json?ref=commit-after-conflict'))return jsonResponse(200,filePayload(incoming));throw new Error(`unexpected ${options.method||'GET'} ${url}`)};const result=await stageHubProduct(incoming,{env,fetchImpl});assert.equal(result.commitSha,'commit-after-conflict');assert.equal(mainReads,2);assert.equal(puts,2)});
test('backlink conflict becomes no-op when concurrent writer already attached the same post',async()=>{const backlink={platform:'x',postId:'x1',url:'https://x.com/i/web/status/x1',publishedAt:'2026-08-14T01:00:00Z'},concurrent=attachBacklinkToProduct(structuredClone(baseProduct),backlink,'2026-08-14T01:01:00Z').product;let reads=0,puts=0;const fetchImpl=async(url,options={})=>{if(url.includes('/data/products/sample-product.json?ref=main')){reads++;return jsonResponse(200,filePayload(reads===1?baseProduct:concurrent,`blob-${reads}`))}if(options.method==='PUT'){puts++;return jsonResponse(409,{message:'sha does not match'})}throw new Error(`unexpected ${options.method||'GET'} ${url}`)};const result=await attachHubSocialBacklink({productId:'sample-product',...backlink},{env,fetchImpl,updatedAt:'2026-08-14T01:01:00Z'});assert.equal(result.changed,false);assert.equal(reads,2);assert.equal(puts,1)});
